=== h3len/digital-heaven/trunk/mkey3g/wwwroot/ec/MKWXCS/mdp.bak.20110407100616/config/mdp-config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:mdp="http://mdp.d-heaven.com" targetNamespace="http://mdp.d-heaven.com" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:annotation>
		<xsd:documentation><![CDATA[ 数字天堂 mdp产品配置文件规范 v1.0 ]]></xsd:documentation>
	</xsd:annotation>
	<!--定义mdp配置-->
	<xsd:element name="configuration">
		<xsd:annotation>
			<xsd:documentation><![CDATA[ 定义mdp配置 ]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<!--访问策略-->
				<xsd:element ref="mdp:authorization"/>
				<!--多数据源支持-->
				<xsd:element ref="mdp:bs-config" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="mdp:db-config" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="mdp:file-config" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="mdp:ftp-config" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="debug" type="xsd:boolean"/>
		</xsd:complexType>
	</xsd:element>
	<!--定义mdp访问策略-->
	<xsd:element name="authorization">
		<xsd:annotation>
			<xsd:documentation><![CDATA[ 
			定义mdp访问策略,allow表示允许访问的数据源；denny表示禁止访问的数据源；如allow="*"表示允许访问所有数据源
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="mdp:allow" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="mdp:deny" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<!--定义允许访问的数据源-->
	<xsd:element name="allow">
		<xsd:annotation>
			<xsd:documentation><![CDATA[ 定义允许访问的数据源 ]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:attribute name="source" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<!--定义禁止访问的数据源-->
	<xsd:element name="deny">
		<xsd:annotation>
			<xsd:documentation><![CDATA[ 定义禁止访问的数据源 ]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:attribute name="source" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<!--定义数据源配置-->
	<!--BS数据源 Start-->
	<xsd:element name="bs-config">
		<xsd:annotation>
			<xsd:documentation><![CDATA[
			定义数据源配置,每一个数据源对应一个bs-config,每个bs-config下可以有多个bs-page,每个bs-page下可以有多个bs-rule 
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="mdp:sso" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="mdp:push" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="mdp:bs-page" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="source" type="xsd:string"/>
			<xsd:attribute name="encoding" default="gb2312">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="gb2312"/>
						<xsd:enumeration value="utf-8"/>
						<xsd:enumeration value="big5"/>
						<xsd:enumeration value="iso8859_1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="header" type="xsd:string"/>
			<xsd:attribute name="footer" type="xsd:string"/>
			<xsd:attribute name="proxyip" type="xsd:string"/>
			<xsd:attribute name="proxyport" type="xsd:int"/>
		</xsd:complexType>
	</xsd:element>
	<!--采集规则集合-->
	<xsd:element name="bs-page">
		<xsd:annotation>
			<xsd:documentation><![CDATA[ 定义采集规则集合 ]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="mdp:bs-rule" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="mdp:bs-frame" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="mdp:bs-params" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:choice>
			<xsd:attribute name="url" type="xsd:string" use="required"/>
			<xsd:attribute name="encoding" default="gb2312">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="gb2312"/>
						<xsd:enumeration value="utf-8"/>
						<xsd:enumeration value="big5"/>
						<xsd:enumeration value="iso8859_1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="title" type="xsd:string"/>
			<xsd:attribute name="isMultiPage" type="xsd:boolean"/>
			<xsd:attribute name="redirectUrl" type="xsd:string"/>
			<xsd:attribute name="accessoryTag" type="xsd:string"/>
			<xsd:attribute name="requestTemplate" type="xsd:string"/>
			<xsd:attribute name="responseTemplate" type="xsd:string"/>
			<xsd:attribute name="target">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="_self|_blank"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="action" type="xsd:string"/>
			<xsd:attribute name="method" type="xsd:string"/>
			<xsd:attribute name="enctype" type="xsd:string"/>
			<xsd:attribute name="page" type="xsd:string"/>
			<xsd:attribute name="decodeRedirectUrl" type="xsd:string"/>
			<xsd:attribute name="escape">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="encode|decode"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<!--框架，采集指定框架的数据-->
	<xsd:element name="bs-frame">
	
		<xsd:complexType>
			<xsd:attribute name="url" type="xsd:string" use="required"/>
			<xsd:attribute name="encoding" default="gb2312">
			<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="gb2312"/>
						<xsd:enumeration value="utf-8"/>
						<xsd:enumeration value="big5"/>
						<xsd:enumeration value="iso8859_1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="regex" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<!--单点登录-->
	<xsd:element name="sso">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="mdp:request" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="sysid" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<!--自动PUSH-->
	<xsd:element name="push">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="mdp:request" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="sysid" type="xsd:string" use="required"/>
			<xsd:attribute name="enterpriseid" type="xsd:string" use="required"/>
			<xsd:attribute name="noticeMsg" type="xsd:string"/>
			<xsd:attribute name="nextAction" type="xsd:string"/>
			<xsd:attribute name="pushType">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="first"/>
						<xsd:enumeration value="all"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<!-- @date:2008-10-18 @author:王志坤-->
		</xsd:complexType>
	</xsd:element>
	<!--HttpRequest-->
	<xsd:element name="request">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="url"/>
				<xsd:element name="params"/>
				<xsd:element name="method" default="GET">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="POST"/>
							<xsd:enumeration value="GET"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="encoding" default="gb2312">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="gb2312"/>
							<xsd:enumeration value="utf-8"/>
							<xsd:enumeration value="big5"/>
							<xsd:enumeration value="iso8859_1"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:string" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<!--变量，解决有些网站登录后生成随机码-->
	<xsd:element name="bs-params">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="mdp:bs-param" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<!--变量，解决有些网站登录后生成随机码-->
	<xsd:element name="bs-param">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="value" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<!--采集规则-->
	<xsd:element name="bs-rule">
		<xsd:annotation>
			<xsd:documentation><![CDATA[ 定义采集规则 ]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="mdp:bs-rule" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attributeGroup ref="mdp:bs-BaseRuleAttribute"/>
			<xsd:attributeGroup ref="mdp:bs-RegexRuleAttribute"/>
			<xsd:attributeGroup ref="mdp:bs-TagRuleAttribute"/>
			<xsd:attributeGroup ref="mdp:bs-ImportRuleAttribute"/>
			<xsd:attributeGroup ref="mdp:bs-JavaRuleAttribute"/>
			<xsd:attributeGroup ref="mdp:bs-JavaScriptRuleAttribute"/>
		</xsd:complexType>
	</xsd:element>
	<!--采集规则基类属性-->
	<xsd:attributeGroup name="bs-BaseRuleAttribute">
		<xsd:attribute name="id" type="xsd:string"/>
		<xsd:attribute name="type" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="regex"/>
					<xsd:enumeration value="tag"/>
					<xsd:enumeration value="java"/>
					<xsd:enumeration value="javascript"/>
					<xsd:enumeration value="import"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="mode">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="add"/>
					<xsd:enumeration value="remove"/>
					<xsd:enumeration value="replace"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="caption" type="xsd:string"/>
		<xsd:attribute name="ref" type="xsd:string"/>
		<xsd:attribute name="replacement" type="xsd:string"/>
		<xsd:attribute name="isTable" type="xsd:boolean"/>
		<xsd:attribute name="template" type="xsd:string"/>
		<xsd:attribute name="escape" type="xsd:string"/>
	</xsd:attributeGroup>
	<!--正则采集规则所有属性-->
	<xsd:attributeGroup name="bs-RegexRuleAttribute">
		<xsd:attribute name="regex" type="xsd:string"/>
	</xsd:attributeGroup>
	<!--标签采集规则所有属性-->
	<xsd:attributeGroup name="bs-TagRuleAttribute">
		<xsd:attribute name="startTag" type="xsd:string"/>
		<xsd:attribute name="endTag" type="xsd:string"/>
	</xsd:attributeGroup>
	<!--java插件支持规则所有属性-->
	<xsd:attributeGroup name="bs-JavaRuleAttribute">
		<xsd:attribute name="className" type="xsd:string"/>
		<xsd:attribute name="method" type="xsd:string"/>
	</xsd:attributeGroup>
	<!--javascript插件支持规则所有属性-->
	<xsd:attributeGroup name="bs-JavaScriptRuleAttribute">
		<xsd:attribute name="filePath" type="xsd:string"/>
		<!--
		<xsd:attribute name="method" type="xsd:string"/>-->
	</xsd:attributeGroup>
	<!--插入规则所有属性-->
	<xsd:attributeGroup name="bs-ImportRuleAttribute">
		<xsd:attribute name="insertAt" type="xsd:string"/>
		<xsd:attribute name="fromIndex" type="xsd:string"/>
		<xsd:attribute name="html" type="xsd:string"/>
	</xsd:attributeGroup>
	<!--BS数据源 End-->
	<!--DB数据源 Start-->
	<xsd:element name="db-config">
		<!--// TODO -->
	</xsd:element>
	<!--DB数据源 End-->
	<!--File数据源 Start-->
	<xsd:element name="file-config">
		<!--// TODO -->
	</xsd:element>
	<!--File数据源 End-->
	<!--FTP数据源 Start-->
	<xsd:element name="ftp-config">
		<!--// TODO -->
	</xsd:element>
	<!--FTP数据源 End-->
</xsd:schema>

=== h3len/digital-heaven/trunk/mkey3g/wwwroot/ec/MKWXCS/mdp.bak.20110407111929/config/20101215_mdp-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE configuration [
    <!--社保查询-珠海-->
    <!ENTITY source1 "218.204.223.149:4044">
    <!ENTITY path1 "http://218.204.223.149:4044">
  <!--社保查询-梅州-->
  <!ENTITY source2 "m.wxcsmz.com">
  <!ENTITY path2 "http://m.wxcsmz.com">
  <!--社保查询-韶关-->
  <!ENTITY source3 "wap.sg12333.cn">
  <!ENTITY path3 "http://wap.sg12333.cn">
  <!--社保查询-揭阳-->
  <!ENTITY source4 "wap.sbt.jymsfw.cn:8080">
  <!ENTITY path4 "http://wap.sbt.jymsfw.cn:8080">
  <!--#################################################################################################-->
  <!--公积金查询-广州-->
  <!ENTITY source5 "210.73.44.165">
  <!ENTITY path5 "http://210.73.44.165">
  <!--公积金查询-东莞-->
  <!ENTITY source6 "wap.dggjj.cn">
  <!ENTITY path6 "http://wap.dggjj.cn">
  <!--公积金查询-梅州-->
  <!ENTITY source7 "m.wxcsmz.com">
  <!ENTITY path7 "http://m.wxcsmz.com">
  <!--公积金查询-云浮-->
  <!ENTITY source8 "wap.umpay.com">
  <!ENTITY path8 "http://wap.umpay.com">
  <!--#################################################################################################-->
  <!--水费查询-梅州-->
  <!ENTITY sourcesf1 "m.wxcsmz.com">
  <!ENTITY pathsf1 "http://m.wxcsmz.com">

  <!--水费查询-云浮-->
  <!ENTITY sourcesf2 "yfwap.uyunfu.com">
  <!ENTITY pathsf2 "http://yfwap.uyunfu.com">
  <!--#################################################################################################-->
  <!--电费查询-珠海-->
  <!ENTITY sourcedf1 "218.204.223.221">
  <!ENTITY pathdf1 "http://218.204.223.221">
]>


<mdp:configuration debug="true" xmlns:mdp="http://mdp.d-heaven.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mdp.d-heaven.com
 mdp-config.xsd">
    <mdp:authorization>
        <mdp:allow source="*"/>
    </mdp:authorization>
  <!--############################################社保查询########################################################################-->
    <!--===============================================社保查询-珠海===========================================-->
  <mdp:bs-config source="&source1;" encoding="utf-8">

    <mdp:bs-page url="&path1;" responseTemplate="shebaocaxun\zhuhai\response_main.xsl" requestTemplate ="shebaocaxun\zhuhai\request_main.xsl"/>
    
  </mdp:bs-config>
    <!--===============================================社保查询-珠海===========================================-->

  <!--===============================================社保查询-梅州===========================================-->
  <mdp:bs-config source="&source2;" encoding="utf-8">

    <mdp:bs-page url="&path2;/" responseTemplate="shebaocaxun\meizhou\response_main.xsl"/>

  </mdp:bs-config>
  <!--===============================================社保查询-梅州===========================================-->

  <!--===============================================社保查询-韶关===========================================-->
  <mdp:bs-config source="&source3;" encoding="utf-8">

    <mdp:bs-page url="&path3;" responseTemplate="shebaocaxun\meizhou\response_main.xsl"/>

  </mdp:bs-config>
  <!--===============================================社保查询-韶关===========================================-->

  <!--===============================================社保查询-揭阳===========================================-->
  <mdp:bs-config source="&source4;" encoding="utf-8">

    <mdp:bs-page url="&path4;" responseTemplate="shebaocaxun\meizhou\response_main.xsl"/>

  </mdp:bs-config>
  <!--===============================================社保查询-揭阳===========================================-->
  <!--############################################社保查询########################################################################-->

  <!--############################################公积金查询########################################################################-->
  <!--===============================================公积金查询-广州===========================================-->
  <mdp:bs-config source="&source5;" encoding="utf-8">

    <mdp:bs-page url="&path5;" responseTemplate="gongjijinchaxun\guangzhou\response_main.xsl"/>

  </mdp:bs-config>
  <!--===============================================公积金查询-广州===========================================-->

  <!--===============================================公积金查询-东莞===========================================-->
  <mdp:bs-config source="&source6;" encoding="utf-8">

    <mdp:bs-page url="&path6;" responseTemplate="gongjijinchaxun\dongguan\response_main.xsl"/>

  </mdp:bs-config>
  <!--===============================================公积金查询-东莞===========================================-->

  <!--===============================================公积金查询-梅州===========================================-->
  <mdp:bs-config source="&source7;" encoding="utf-8">

    <mdp:bs-page url="&path7;" responseTemplate="gongjijinchaxun\meizhou\response_main.xsl"/>

  </mdp:bs-config>
  <!--===============================================公积金查询-梅州===========================================-->

  <!--===============================================公积金查询-云浮===========================================-->
  <mdp:bs-config source="&source8;" encoding="utf-8">

    <mdp:bs-page url="&path8;" responseTemplate="gongjijinchaxun\yunfu\response_main.xsl"/>

  </mdp:bs-config>
  <!--===============================================公积金查询-云浮===========================================-->
  <!--############################################公积金查询########################################################################-->



  <!--############################################水费查询########################################################################-->
  <!--===============================================水费查询-梅州===========================================-->
  <mdp:bs-config source="&sourcesf1;" encoding="utf-8">
    <!--首页-->
    <mdp:bs-page url="&pathsf1;/wapquery/menu/sfSelect.jsp\?id=\d+" responseTemplate="sf_search\meizhou\response_main.xsl"/>
    <!--查询-->
    <mdp:bs-page url="&pathsf1;/wapquery/menu/sfinterfaceinfo.jsp\?method=post" responseTemplate="sf_search\meizhou\response_search.xsl"/>
    <mdp:bs-page url="&pathsf1;/wapquery/menu/sfinterfacedetail.jsp" responseTemplate="sf_search\meizhou\response_detail.xsl"/>
    <mdp:bs-page url="&pathsf1;/wapquery/menu/sfoldwaterselect.jsp" responseTemplate="sf_search\meizhou\response_detail.xsl"/>
  </mdp:bs-config>
  <!--===============================================水费查询-梅州===========================================-->

  <!--===============================================水费查询-云浮===========================================-->
  <mdp:bs-config source="&sourcesf2;" encoding="utf-8">
    <mdp:bs-page url="&pathsf2;/SfQuery.aspx" responseTemplate="sf_search\yunfu\response_main.xsl" requestTemplate ="sf_search\yunfu\request_search.xsl"/>
    <mdp:bs-page url="&pathsf2;/Sfinfo.aspx\?hh=(.*)" responseTemplate="sf_search\yunfu\response_main.xsl"/>
  </mdp:bs-config>
  <!--===============================================水费查询-云浮===========================================-->
  <!--############################################水费查询########################################################################-->

  <!--############################################电费查询########################################################################-->
  
  <!--===============================================电费查询-珠海===========================================-->
  <mdp:bs-config source="&sourcedf1;" encoding="utf-8">
    <mdp:bs-page url="&pathdf1;/zhgwap/gov/bmfwjt/dfcx.jsp" responseTemplate="df_search\zhuhai\response_main.xsl" requestTemplate ="df_search\zhuhai\request_search.xsl"/>
    <mdp:bs-page url="&pathdf1;/Sfinfo.aspx\?hh=(.*)" responseTemplate="sf_search\yunfu\response_main.xsl"/>
  </mdp:bs-config>

  <!--===============================================电费查询-珠海===========================================-->
  <!--############################################电费查询########################################################################-->
</mdp:configuration>

=== h3len/digital-heaven/mkey3g/mdp/config/mdp-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE configuration [
  <!--定义数据源-->
  <!ENTITY source "www.changping.gov.cn">
  <!ENTITY path "http://www.changping.gov.cn">

  <!ENTITY source1 "www.cp.gov.cn">
  <!ENTITY path1 "http://www.cp.gov.cn">
  
  <!ENTITY source2 "www.dgaic.gov.cn">
  <!ENTITY path2 "http://www.dgaic.gov.cn">
  
  <!ENTITY source3 "www.dgzmt.gov.cn">
  <!ENTITY path3 "http://www.dgzmt.gov.cn">

  <!ENTITY source4 "www.jmnews.com.cn">
  <!ENTITY path4 "http://www.jmnews.com.cn">
]>

<mdp:configuration xmlns:mdp="http://mdp.d-heaven.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" debug="true" xsi:schemaLocation="http://mdp.d-heaven.com mdp-config.xsd">
  <mdp:authorization>
    <mdp:allow source="*"/>
  </mdp:authorization>

  <mdp:bs-config source="&source4;" encoding="gb2312">
    <!--江门新闻网_本地新闻主页-->
    <mdp:bs-page url="&path4;/$" responseTemplate="jmnews/response_index.xsl" encoding="gb2312"/>
	<mdp:bs-page url="&path4;/web/sort.aspx\?sort_id=\w+" responseTemplate="jmnews/response_local.xsl" encoding="gb2312"/>
	<!--<mdp:bs-page url="&path4;/c/\w+/\w+/\w+/\w+/c_\w+.shtml" responseTemplate="jmnews/response_content.xsl" encoding="gb2312"/>-->
	<mdp:bs-page url="&path4;/c/\w+/\w+/\w+/\w+/c_\w+.shtml" responseTemplate="jmnews/response_content_ad.xsl" encoding="gb2312"/>
  </mdp:bs-config>

  <!--江门新闻网图片-->
  <mdp:bs-config source="http://image.jmrb.com" encoding="gb2312"/>

  <mdp:bs-config source="&source3;" encoding="UTF-8">
    <!--樟木头主页-->
    <mdp:bs-page url="&path3;/publicfiles/business/htmlfiles/dgzmt/index.htm" responseTemplate="zmt/response_index.xsl" encoding="UTF-8"/>
    <mdp:bs-page url="&path3;/publicfiles//business/htmlfiles/dgzmt/s\d+/index.htm" responseTemplate="zmt/response_notice.xsl" encoding="UTF-8">
    	<mdp:bs-rule type="regex" regex="&lt;INFO>      &lt;Title>([^&lt;]+)&lt;/Title>      &lt;SubTitle />      (&lt;ExpStr1>([^&lt;]+)&lt;/ExpStr1>|&lt;ExpStr1 />)      &lt;PublishedTime>([^&lt;]+)&lt;/PublishedTime>      (&lt;Source>([^&lt;]+)&lt;/Source>|&lt;Source />)      &lt;ParentCateId>([^&lt;]+)&lt;/ParentCateId>      &lt;InfoURL>([^&lt;]+)&lt;/InfoURL>    &lt;/INFO>" template="&lt;div name=$1 date=$4 href='/publicfiles/business/htmlfiles/$8' />"/>
    </mdp:bs-page>

    <mdp:bs-page url="&path3;/publicfiles/business/htmlfiles/dgzmt/s\d+/\d+/\d+.htm" responseTemplate="zmt/response_content.xsl" encoding="UTF-8">
    	</mdp:bs-page>
  </mdp:bs-config>
  
  <mdp:bs-config source="&source2;" encoding="gb2312" cacheTime="0">
    <mdp:bs-page url="&path2;/$" responseTemplate="test/response_index.xsl" encoding="gb2312">
    	<mdp:bs-frame url="&path2;/item.jsp?id=25000051&amp;name=消费警示&amp;type=1"/>
    	<!--<mdp:bs-frame url="&path2;/item.jsp?id=25000046&amp;name=行政公告&amp;type=1"/>-->
    </mdp:bs-page>
    <mdp:bs-page url="&path2;/readArticle.jsp" responseTemplate="test/response_content.xsl" encoding="gb2312"/>
    <mdp:bs-page url="&path2;/item.jsp?id=25000046" responseTemplate="test/response_zfggcontent.xsl" encoding="gb2312"/>
  </mdp:bs-config>
  
  <mdp:bs-config source="wsnj.gdgs.gov.cn" encoding="gb2312" cacheTime="0">
  	<mdp:bs-page url="http://wsnj.gdgs.gov.cn/aiccps/jsp/pub/searchBase.jsp\?returnUP=true" responseTemplate="test/response_search.xsl" requestTemplate="test/request_searchcx.xsl" encoding="gb2312"/>
  	<!--<mdp:bs-page url="http://wsnj.gdgs.gov.cn/aiccps/SearchServlet" responseTemplate="test/response_search.xsl" encoding="gb2312"/>-->
  </mdp:bs-config>

<mdp:bs-config source="&source;" encoding="gb2312">
    <!--主页-->
    <mdp:bs-page url="&path;/$" responseTemplate="response_index.xsl" encoding="gb2312">
      <mdp:bs-frame url="http://www.cp.gov.cn/newver/03xinwen/05redian.asp?c_id=106"/>
      <mdp:bs-frame url="http://www.cp.gov.cn/newver/03xinwen/03redian.asp"/>
      <mdp:bs-frame url="http://www.cp.gov.cn/newver/02zhengfu/zfcg.asp?c_id=18"/>
    </mdp:bs-page>
  </mdp:bs-config>


  <!--政务公开——-->
  <mdp:bs-config source="xxgk.dg.gov.cn" encoding="utf-8">
    <!--常平简介-->
    <mdp:bs-page url="http://xxgk.dg.gov.cn/publicfiles/business/htmlfiles/\d+/\d*.\d*/\d+/\d+.htm" responseTemplate="cpzf/response_xq.xsl" encoding="utf-8"/>

  </mdp:bs-config>


  <mdp:bs-config source="&source1;" encoding="gb2312">
    <!--主页-->
    <mdp:bs-page url="&path1;/$" responseTemplate="response_index.xsl" encoding="gb2312">
      <mdp:bs-frame url="http://www.cp.gov.cn/newver/03xinwen/05redian.asp?c_id=106"/>
      <mdp:bs-frame url="http://www.cp.gov.cn/newver/03xinwen/03redian.asp"/>
      <mdp:bs-frame url="http://www.cp.gov.cn/newver/02zhengfu/zfcg.asp?c_id=18"/>
    </mdp:bs-page>
    <!--政府公告-->
    <mdp:bs-page url="&path1;/newver/03xinwen/05redian.asp" responseTemplate="cpzf/response_zfgg.xsl" encoding="gb2312"/>
    <!--政府公告_分页后带参数-->
    <!--<mdp:bs-page url="&path1;/newver/03xinwen/05redian.asp\?page=\d+&amp;c_id=\d+" responseTemplate="cpzf/response_zfgg.xsl" encoding="gb2312"/>-->
    <!--公告详情、热点报道详情-->
    <mdp:bs-page url="&path1;/htm/info/infoshow_\d+.htm" responseTemplate="cpzf/response_zfgg_xq.xsl" encoding="gb18030"/>
    <!--热点报道-->
    <mdp:bs-page url="&path1;/newver/03xinwen/03redian.asp" responseTemplate="cpzf/response_rdbd.xsl" encoding="gb2312"/>
    <!--常平信息-->
    <mdp:bs-page url="&path1;/newver/03xinwen/news.asp" responseTemplate="cpzf/response_cpxx.xsl" encoding="gb2312"/>
    <!--常平信息详情-->
    <mdp:bs-page url="&path1;/htm/news/nshow_\d+.htm" responseTemplate="cpzf/response_zfgg_xq.xsl" encoding="gb18030"/>
    <!--共青团讯-->
    <mdp:bs-page url="&path1;/newver/02zhengfu/tx123.asp" responseTemplate="cpzf/response_gqtx.xsl" encoding="gb2312"/>
    <!--政府采购-->
    <mdp:bs-page url="&path1;/newver/02zhengfu/zfcg.asp" responseTemplate="cpzf/response_zfcg.xsl" encoding="gb2312"/>
    <!--镇长信箱-->
    <mdp:bs-page url="&path1;/newver/07renxian/zzxx.asp" responseTemplate="cpzf/response_zzxx.xsl" requestTemplate="cpzf/request_zzxx.xsl" encoding="gb18030"/>
    <!--给镇长写信_信箱使用须知-->
    <mdp:bs-page url="&path1;/newver/07renxian/sendmail1.asp" responseTemplate="cpzf/response_sendmail_warning.xsl" encoding="gb2312"/>
    <!--给镇长写信-->
    <mdp:bs-page url="&path1;/newver/07renxian/sendmail2.asp" responseTemplate="cpzf/response_sendmail.xsl" requestTemplate="cpzf/request_sendmail.xsl" encoding="gb2312"/>
    <!--给镇长写信-提交写信-->
    <mdp:bs-page url="&path1;/newver/07renxian/Add_Question_ToDB.asp" responseTemplate="cpzf/response_sendmail_ok.xsl" encoding="gb2312">
      <mdp:bs-rule regex="&lt;script language='javascript'&gt;alert\('([^&apos;]+)'\);" type="regex" template="&lt;div id='servermsg_ok' value='$1'/&gt;"/>
    </mdp:bs-page>
    <!--联系我们-->
    <mdp:bs-page url="&path1;/\?show=lxwm$" responseTemplate="response_index.xsl" encoding="gb2312"/>

  </mdp:bs-config>
  <mdp:bs-config source="127.0.0.1:8080" encoding="gb2312"/>
</mdp:configuration>

=== h3len/digital-heaven/mkey3g/wwwroot/ec/MKGYGG/mdp/config/mdp-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE configuration[
  <!--高雅广告-->
  <!ENTITY source_gygg "www.chinagaoya.com">
  <!--高雅广告-->
  <!ENTITY path_gygg "http://www.chinagaoya.com">
]>

<mdp:configuration xmlns:mdp="http://mdp.d-heaven.com"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://mdp.d-heaven.com  mdp-config.xsd">

  <mdp:authorization>
    <mdp:allow source="*" />
  </mdp:authorization>

  <!--高雅广告-->
  <mdp:bs-config source="&source_gygg;" encoding="gb18030" htmlToXmlProvider="JTIDY" parseType="transfer" retryCount="3">
    <!--首页-->
    <mdp:bs-page url="&path_gygg;/index1.asp" responseTemplate="gygg/response_index.xsl">
    </mdp:bs-page>
    <!--公司简介-->
    <mdp:bs-page url="&path_gygg;/gsjj.asp" responseTemplate="gygg/response_fwfw.xsl"/>
    <!--服务范围-->
    <mdp:bs-page url="&path_gygg;/service1.asp" responseTemplate="gygg/response_fwfw.xsl"/>
    <mdp:bs-page url="&path_gygg;/service2.asp" responseTemplate="gygg/response_fwfw.xsl"/>
    <!--最新动态-->
    <mdp:bs-page url="&path_gygg;/otype.asp\?owen1" responseTemplate="gygg/response_zxdt.xsl"/>
    <mdp:bs-page url="&path_gygg;/onews.asp\?id=" responseTemplate="gygg/response_zxdt.xsl"/>
    <!--诚聘精英-->
    <mdp:bs-page url="&path_gygg;/otype1.asp\?owen1" responseTemplate="gygg/response_zxdt.xsl"/>
    <!--作品栏-->
    <mdp:bs-page url="&path_gygg;/photos/type.asp\?typeid=26" responseTemplate="gygg/response_zpl.xsl"/>
    <mdp:bs-page url="&path_gygg;/photos/display.asp\?id" responseTemplate="gygg/response_zplnr.xsl"/>
  </mdp:bs-config>


</mdp:configuration>
